'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Resource1
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PawfessionalApp.Resource1", GetType(Resource1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property cat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Cat_Deodorant_Powder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cat Deodorant Powder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Charco_s_Beef_Dog_Treats() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Charco's Beef Dog Treats", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Charco_s_Original_Dog_Treats() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Charco's Original Dog Treats", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property cosi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cosi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property customericon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("customericon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Dr__Healmedix_Hepatic_1_5kg_Dog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dr. Healmedix Hepatic 1.5kg Dog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property fipronilspray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fipronilspray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Furfect_Soap_Biosulfur_Madre_de_cacao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Furfect Soap Biosulfur+Madre de cacao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property HEPATOSURE_Sorbitol_Inositol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HEPATOSURE Sorbitol Inositol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Kitekat_Wet_Cat_Food_Chicken_and_Salmon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kitekat Wet Cat Food Chicken and Salmon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Kitekat_Wet_Cat_Food_Chicken_and_Tuna() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kitekat Wet Cat Food Chicken and Tuna", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property lc_vit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lc vit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Madre_Bar_Soup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Madre Bar Soup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Mondex_Water_Soluble_Powder_340g() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mondex Water Soluble Powder 340g", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Nutripe_Dog_Food_Beef_And_Green_Tripe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nutripe Dog Food Beef And Green Tripe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Nutripe_Lamb_and_Green_Tripe_Pure() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nutripe Lamb and Green Tripe Pure", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property papi_cologne() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("papi cologne", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Papi_Groom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Papi Groom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Pedigree_Adult_Beef_in_Gravy_Wet_Dog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pedigree Adult Beef in Gravy Wet Dog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Pedigree_DENTASTIX_Daily_oral_care() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pedigree DENTASTIX Daily oral care", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Pedigree_Puppy_Chicken_Chunks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pedigree Puppy Chicken Chunks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property PEDIGREE_PUPPY_WET_DOG_FOOD_BEEF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEDIGREE PUPPY WET DOG FOOD BEEF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Persian_Kitten_Dry_Cat_Food() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Persian Kitten Dry Cat Food", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Petdelyte_Oral_Solution() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Petdelyte Oral Solution", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Royal_Canin_Breed_Health_Nutrition() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Royal Canin Breed Health Nutrition", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Royal_Canin_Hairball_Care() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Royal Canin Hairball Care", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Royal_Canin_Hepatic_Adult_Wet_Dog_Food() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Royal Canin Hepatic Adult Wet Dog Food", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Royal_Canin_Recovery_for_Dogs_and_Cats() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Royal Canin Recovery for Dogs and Cats", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Royal_Canin_Renal_Can_Wet_Food() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Royal Canin Renal Can Wet Food", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Royal_Canin_Veterinary_Canine_Urinary() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Royal Canin Veterinary Canine Urinary", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Royal_Canin_Veterinary_Gastrointestinal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Royal Canin Veterinary Gastrointestinal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Royal_Tail_ear_Cleanser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Royal Tail ear Cleanser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Royal_Tail_Essentials_Madre_de_Cacao_dog_soup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Royal Tail Essentials Madre de Cacao dog soup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Royal_Tail_Essentials_Madre_de_Tutti_Frutiepng() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Royal Tail Essentials Madre de Tutti Frutiepng", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Royal_Tail_Shampoo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Royal Tail Shampoo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Royal_Tail_Sweet_Talk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Royal Tail Sweet Talk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property SHEBA_WET_CAT_FOOD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SHEBA WET CAT FOOD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property SlicesGravy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SlicesGravy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Special_Delight_Tuna_and_Ocean_Fish() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Special Delight Tuna and Ocean Fish", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Special_Delight_Tuna_and_Salmon_Mousse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Special Delight Tuna and Salmon Mousse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Specialbeef_removebg_preview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Specialbeef-removebg-preview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Toothpaste_Chicken_Flavor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Toothpaste Chicken Flavor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Toothpaste_Orange_Flavor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Toothpaste Orange Flavor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Toothpaste_with_Beef_Flavor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Toothpaste with Beef Flavor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Toothpaste_with_Mint_Flavor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Toothpaste with Mint Flavor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Tuna_Cat_Food_Pouch_for_Adult() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tuna Cat Food Pouch for Adult", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property user_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Value_Meal_Dog_food() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Value Meal Dog food", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Vitality_Classic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vitality Classic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Vitality_High_Energy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vitality High Energy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Vitality_Valuemeal_Dog_Food_Grain_Free() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vitality Valuemeal Dog Food Grain Free", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Whiskas_Junior_Mackerel_Wet_Cat_Food() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Whiskas Junior Mackerel Wet Cat Food", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Whiskas_Junior_Tuna_Wet_Cat_Food() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Whiskas Junior Tuna Wet Cat Food", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property Wound_Spray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wound Spray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public Shared ReadOnly Property xavier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xavier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
